import "./globals.css";
import { Inter } from "next/font/google";
import { MenuAside } from "./components/MenuAside";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex grid-cols-2">
					<MenuAside />
					<div className="flex-1 sm:ml-20 px-16">{children}</div>
				</div>
			</body>
		</html>
	);
}
